### ISSUE TITLE
High scores are overwritten after each playthrough

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TheEnginesOfCreation/EntityPlus#172]
```
When finishing a level, only the score of that play-through is saved to the 
highscores file for that map. An existing score is lost.
```

Original issue reported on code.google.com by `era...@gmail.com` on 18 Mar 2014 at 10:56

**Comment by TheEnginesOfCreation** [comment]
When compiled as qvm, the problem persists even in 1.1.5

**Comment by TheEnginesOfCreation** [comment]
The problem is caused by sv_pure being set to 1. The highscore file is outside of a pk3 file and can therefore not be read when the game tries to load existing scores. Setting sv_pure to 0 fixes this.
Will try to see if sv_pure can always be forced to 0 in EntityPlus.
